import type { Playlist, Theme, GiftConfig } from './types';

export const DEFAULT_GIFT_CONFIG: GiftConfig = {
  friendName: "Bestie 🌸",
  tagline: "Drive Safe, Sparkle Always ✨",
  message: "A non-stop aesthetic playlist crafted with love. Press play & enjoy the vibe! 💖",
  customTitle: "Music",
  hindiTitle: "मेरी पसंदीदा",
  isGiftMode: true,
};

export const THEMES: Record<string, Theme> = {
  princess: {
    id: 'princess',
    name: 'Princess Pink 🌸',
    icon: '🌸',
    bgGradient: 'from-[#1a0b16] via-[#2a0e23] to-[#0d0714]',
    primaryColor: '#f472b6',
    accentColor: '#fb7185',
    dockBg: 'rgba(255, 182, 193, 0.12)',
    fontClass: 'font-outfit',
    taglineFont: 'font-sacramento',
    particles: 'sparkles',
    cardGlow: '0 8px 32px 0 rgba(244, 114, 182, 0.25)',
  },
  'cozy-sunset': {
    id: 'cozy-sunset',
    name: 'Cozy Sunset 🎀',
    icon: '🎀',
    bgGradient: 'from-[#1c1024] via-[#2d1829] to-[#120a16]',
    primaryColor: '#fb923c',
    accentColor: '#f472b6',
    dockBg: 'rgba(251, 146, 60, 0.12)',
    fontClass: 'font-outfit',
    taglineFont: 'font-sacramento',
    particles: 'clouds',
    cardGlow: '0 8px 32px 0 rgba(251, 146, 60, 0.25)',
  },
  'pop-queen': {
    id: 'pop-queen',
    name: 'Pop Queen 💖',
    icon: '💖',
    bgGradient: 'from-[#1e0a2b] via-[#350f38] to-[#100517]',
    primaryColor: '#e879f9',
    accentColor: '#c084fc',
    dockBg: 'rgba(232, 121, 249, 0.14)',
    fontClass: 'font-outfit',
    taglineFont: 'font-outfit',
    particles: 'stars',
    cardGlow: '0 8px 32px 0 rgba(232, 121, 249, 0.25)',
  },
  lavender: {
    id: 'lavender',
    name: 'Lavender Night 💜',
    icon: '💜',
    bgGradient: 'from-[#0f0e26] via-[#1a1842] to-[#090817]',
    primaryColor: '#a78bfa',
    accentColor: '#818cf8',
    dockBg: 'rgba(167, 139, 250, 0.12)',
    fontClass: 'font-outfit',
    taglineFont: 'font-outfit',
    particles: 'hearts',
    cardGlow: '0 8px 32px 0 rgba(167, 139, 250, 0.25)',
  },
  'truck-highway': {
    id: 'truck-highway',
    name: 'Classic Truck Highway 🚛',
    icon: '🚛',
    bgGradient: 'from-[#080d12] via-[#0d1620] to-[#05080c]',
    primaryColor: '#f59e0b',
    accentColor: '#ef4444',
    dockBg: 'rgba(245, 158, 11, 0.12)',
    fontClass: 'font-baloo',
    taglineFont: 'font-rozha',
    particles: 'highway',
    cardGlow: '0 8px 32px 0 rgba(245, 158, 11, 0.25)',
  },
};

export const GIRL_TAGLINES = [
  "Princess on the Wheel 👑",
  "Drive Safe, Sparkle Always ✨",
  "No Drama, Just Music 💖",
  "Good Vibes & Long Drives 🌸",
  "Main Apni Favorite Hoon 💅",
  "Hass Mat Pagli, Pyaar Ho Jayega 😉",
  "Buri Nazar Wale Tera Muh Kaala 🧿",
  "Dil Toh Bachha Hai Ji 🎈",
  "Cute But Dangerous 🎀",
  "Chasing Sunsets & Music 🌅",
];

export const PRESET_PLAYLISTS: Playlist[] = [
  {
    id: 'truck-driver-original',
    name: 'Indian Highway Truck Bangers',
    description: 'The non-stop Punjabi, Hindi & Bhojpuri highway songs blasting out of Indian trucks.',
    category: 'highway-truck',
    icon: '🚛',
    youtubeListId: 'PLgObA3pAqvOh87Z03QG8Z4xE-uqlAWSBy',
    items: [
      { id: '1qZ8S7V6M4w', title: 'Highway Highway Beats', artist: 'Punjabi Truck Anthems', thumbnail: 'https://img.youtube.com/vi/1qZ8S7V6M4w/hqdefault.jpg' },
      { id: 'Y7dpJ0oseIA', title: 'Subah Subah Dhaba Hits', artist: 'Highway Folk', thumbnail: 'https://img.youtube.com/vi/Y7dpJ0oseIA/hqdefault.jpg' },
      { id: 'h7J_r1p8gKw', title: 'Horn OK Please Highway Jam', artist: 'Truck Driver Music', thumbnail: 'https://img.youtube.com/vi/h7J_r1p8gKw/hqdefault.jpg' },
    ],
  },
  {
    id: 'girl-boss-pop',
    name: 'Girl Boss Highway Anthems',
    description: 'Upbeat pop, Punjabi bops & fierce female anthems for the ultimate drive.',
    category: 'girl-boss',
    icon: '🌸',
    youtubeListId: 'PL4fGSI1pDJn6O1LS0XSdF3RyO0Rq_LDeI',
    items: [
      { id: 'hT_nvWreIhg', title: 'Counting Stars / Pop Anthems', artist: 'Pop Queens', thumbnail: 'https://img.youtube.com/vi/hT_nvWreIhg/hqdefault.jpg' },
      { id: '09R8_2nJtjg', title: 'Girl Boss Roadtrip Beats', artist: 'Top Pop Hits', thumbnail: 'https://img.youtube.com/vi/09R8_2nJtjg/hqdefault.jpg' },
    ],
  },
  {
    id: 'cozy-lofi-sunset',
    name: 'Cozy Midnight Lofi Drive',
    description: 'Relaxing aesthetic chillbeats & atmospheric lofi highway rain vibes.',
    category: 'cozy-lofi',
    icon: '🎀',
    youtubeListId: 'PLOFnL4rN0bch5U63VWe0y52cT4FknduUv',
    items: [
      { id: 'jfKfPfyJRdk', title: 'lofi hip hop radio - beats to relax/study to', artist: 'Lofi Girl', thumbnail: 'https://img.youtube.com/vi/jfKfPfyJRdk/hqdefault.jpg' },
      { id: '5qap5aO4i9A', title: 'Lofi Highway Sunset Rain', artist: 'Chill Beats', thumbnail: 'https://img.youtube.com/vi/5qap5aO4i9A/hqdefault.jpg' },
    ],
  },
  {
    id: 'bollywood-romantic-drive',
    name: 'Bollywood Sunset Romance',
    description: 'Melodic 90s & 2000s Hindi drive hits for long journeys.',
    category: 'romantic',
    icon: '🍯',
    youtubeListId: 'PL9bw4S5AgErqP2GVsGfQWq_u95Xw483L1',
    items: [
      { id: 'dTU5TvdX00E', title: 'Tum Hi Ho / Melodic Romance', artist: 'Bollywood Romance', thumbnail: 'https://img.youtube.com/vi/dTU5TvdX00E/hqdefault.jpg' },
      { id: 'k4yXQkGg3X4', title: 'Hindi Sunset Highway Jams', artist: 'Arijit & Friends', thumbnail: 'https://img.youtube.com/vi/k4yXQkGg3X4/hqdefault.jpg' },
    ],
  },
];
