name: Trigger auto deployment for opsmeld-recon-app

on:
  push:
    branches: 
      [ main ]
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.OPSMELDRECONAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.OPSMELDRECONAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.OPSMELDRECONAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Log in to ACR and Build/Push Docker Image
        run: |
          az acr login --name acropsmeldrecon
          docker build -t acropsmeldrecon.azurecr.io/opsmeld-recon-app:${{ github.sha }} -t acropsmeldrecon.azurecr.io/opsmeld-recon-app:latest .
          docker push acropsmeldrecon.azurecr.io/opsmeld-recon-app:${{ github.sha }}
          docker push acropsmeldrecon.azurecr.io/opsmeld-recon-app:latest

      - name: Deploy to Azure Container App
        run: |
          az acr update --name acropsmeldrecon --admin-enabled true
          ACR_PASS=$(az acr credential show --name acropsmeldrecon --query "passwords[0].value" -o tsv)
          az containerapp registry set \
            --name opsmeld-recon-app \
            --resource-group rg-opsmeld-container \
            --server acropsmeldrecon.azurecr.io \
            --username acropsmeldrecon \
            --password $ACR_PASS
          az containerapp update \
            --name opsmeld-recon-app \
            --resource-group rg-opsmeld-container \
            --image acropsmeldrecon.azurecr.io/opsmeld-recon-app:${{ github.sha }}
